# ipmiserial - IPMI Serial-over-LAN console server
# Deploy via: oc --server=http://api.rose1.gt.lo:8082 apply -f deploy/ipmiserial.yaml

apiVersion: v1
kind: Pod
metadata:
  name: ipmiserial
  namespace: g11
  annotations:
    vkube.io/network: g11
    vkube.io/boot-priority: "70"
    vkube.io/depends-on: "g11_dns_microdns"
    vkube.io/image-policy: auto
    vkube.io/aliases: "ipmiserial"
spec:
  restartPolicy: Always
  containers:
    - name: ipmiserial
      image: 192.168.200.2:5000/ipmiserial:edge
      livenessProbe:
        httpGet:
          path: /
          port: 80
        periodSeconds: 30
        failureThreshold: 3
      volumeMounts:
        - name: data
          mountPath: /var/lib/data
